<field:story_title itemname="标题" autofield="1" notsend="0" type="textchar" isnull="true" islist="1" default="输入标题"  maxlength="250" page="">
</field:story_title>

<field:story_site itemname=" 案例地址" autofield="1" notsend="0" type="textchar" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:story_site>

<field:story_bigimg itemname="网站截图" autofield="1" notsend="0" type="img" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:story_bigimg>


<field:story_logo itemname="上传LOGO图" autofield="1" notsend="0" type="img" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:story_logo>
