[field:sorty_title/]
			{dede:list}





	        <div class="case_item">
	            <div class="case_img"><img src="images/example/dyd.png" /></div>
	            <div class="case_text">
	                <h3>东营贷</h3>
	                <p>吉诺东营贷是经工信部备案、官方权威认证的P2P互联网金融平台...</p>
	            </div>
	             <div class="case_btns">
	            	<a class="btn btn_case_pink" href="http://www.dongyingdai.cn" target="_blank">登录网站<em class="icos"></em></a>
	              	<a class="btn btn_case_lblue" href="storyDetaildydx.html">查看详情<em class="icos"></em></a>
	            </div>
	
	        </div>

	        <div class="case_item">
	            <div class="case_img"><img src="images/example/lele.png" /></div>
	            <div class="case_text">
	                <h3>乐乐理财</h3>
	                <p>乐乐理财是由北京柒柒网络科技有限公司筹建的经官方权威认证...</p>
	               
	            </div>
	            <div class="case_btns">
	            	<a class="btn btn_case_pink" href="http://www.33.net.cn/" target="_blank">登录网站<em class="icos"></em></a>
	              	<a class="btn btn_case_lblue" href="storyDetaillele.html">查看详情<em class="icos"></em></a>
	            </div>
	        </div>

	         <div class="case_item">
	            <div class="case_img"><img src="images/example/taq.png" /></div>
	            <div class="case_text">
	                <h3>太安全</h3>
	                <p>太安全，系泰安市众诚金融信息服务有限公司旗下独立品牌...</p>
	            
	            </div>
	            <div class="case_btns">
	            	<a class="btn btn_case_pink" href="http://www.taianquan.com" target="_blank">登录网站<em class="icos"></em></a>
	              	<a class="btn btn_case_lblue" href="storyDetailTaq.html">查看详情<em class="icos"></em></a>
	            </div>
	        </div>



	          <div class="case_item">
	            <div class="case_img"><img src="images/example/jml.png" /></div>
	            <div class="case_text">
	                <h3>聚梦利</h3>
	                <p>北京聚梦利管理咨询有限公司是依据《中华人民共和国担保法...</p>
	            
	            </div>
	            <div class="case_btns">
	            	<a class="btn btn_case_pink" href="http://www.jumengli.com" target="_blank">登录网站<em class="icos"></em></a>
	              	<a class="btn btn_case_lblue" href="storyDetailjml.html">查看详情<em class="icos"></em></a>
	            </div>
	        </div>

	        
	        
	      
	       
	      
	       
	        
	        
	       
	        
	       
	        
	       
	       
		</div>

		<!--select 选中
				<em class="current">1</em>
				<a href="#" class="pageindex" currentNum="2">2</a>
				<a href="#" class="pageindex" currentNum="3">3</a>
		<a href="#" class="pageindex" currentNum="2">下一页</a>
		<a href="#" class="page" currentNum="3">尾页</a>
		</div>

	    </div> -->
	</div>
</form>
{dede:include filename="foot.htm"