<div class="case_item">
	            <div class="case_img"><img src="[field:story_title/]" /></div>
	            <div class="case_text">
	                <h3>东营贷</h3>
	                <p>吉诺东营贷是经工信部备案、官方权威认证的P2P互联网金融平台...</p>
	            </div>
	             <div class="case_btns">
	            	<a class="btn btn_case_pink" href="http://www.dongyingdai.cn" target="_blank">登录网站<em class="icos"></em></a>
	              	<a class="btn btn_case_lblue" href="storyDetaildydx.html">查看详情<em class="icos"></em></a>
	            </div>
	
	        </div>