<div class="case_item">
		            <div class="case_img"><img src="[field:story_bigimg function='GetOneImgUrl(@me,1)'/]" /></div>
		            <div class="case_text">
		                <h3>[field:story_title/]</h3>
		                <p>[field:story_discribe function='(strlen("@me")>64?cn_substr("@me",64)."…" : "@me" )'/]</p>
		            </div>
		             <div class="case_btns">
		            	<a class="btn btn_case_pink" href="[field:story_site/]" target="_blank">登录网站<em class="icos"></em></a>
		              	<a class="btn btn_case_lblue" href="[field:arcurl/]">查看详情<em class="icos"></em></a>
		            </div>
		
		        </div>