<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="1";
$z[1]=Array("img"," /uploads/allimg/150917/1-15091G15025.png ",93,239);
$z[1][4]['ddimg']="/uploads/allimg/150917/1-15091G15025.png";
$z[1][4]['text']="";
$z[1][4]['width']="1920";
$z[1][4]['height']="224";
$z[2]=Array("img"," /uploads/allimg/150917/1-15091G15031.png ",241,386);
$z[2][4]['ddimg']="/uploads/allimg/150917/1-15091G15031.png";
$z[2][4]['text']="";
$z[2][4]['width']="384";
$z[2][4]['height']="158";

?>