<?php
$z[0]=Array("global","",122,154);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("channel","\r\n            <a href='[field:typeurl/]' [field:rel/]>[field:typename/]</a> | \r\n            ",315,512);
$z[1][4]['type']="top";
$z[1][4]['row']="5";
$z[1][4]['currentstyle']="<a href='~typelink~' ~rel~>~typename~</a>";
$z[2]=Array("global","",555,577);
$z[2][4]['name']="address";
$z[3]=Array("global","",594,620);
$z[3][4]['name']="cfg_powerby";

?>