<?php
$z[0]=Array("adminname","",0,18);
$z[1]=Array("global","",124,151);
$z[1][4]['name']="cfg_basehost";
$z[2]=Array("global","",163,195);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",242,268);
$z[3][4]['name']="cfg_webname";
$z[4]=Array("myad","",323,358);
$z[4][4]['name']="innerTopBanner1";
$z[5]=Array("myad","",393,428);
$z[5][4]['name']="innerTopBanner2";
$z[6]=Array("global","",731,756);
$z[6][4]['name']="cfg_cmsurl";
$z[7]=Array("channel","\r\n      	<li><a href='[field:typeurl/]' [field:rel/]><span>[field:typename/]</span></a></li>\r\n      	",796,1039);
$z[7][4]['type']="top";
$z[7][4]['row']="10";
$z[7][4]['currentstyle']="<li class='hover'><a href='~typelink~' ~rel~><span>~typename~</span></a></li>";
$z[8]=Array("global","",1131,1156);
$z[8][4]['name']="cfg_cmsurl";
$z[9]=Array("tag","\r\n            <li><a href='[field:link/]'>[field:tag /]</a></li>\r\n          ",1964,2094);
$z[9][4]['row']="10";
$z[9][4]['getall']="1";
$z[9][4]['sort']="month";

?>